GENERIC_PLUGIN_WIDGET_WIDTH = 165
GENERIC_PLUGIN_WIDGET_HEIGHT = 35
GENERIC_PLUGIN_WIDGET_Y_OFFSET = 30
GENERIC_PLUGIN_WIDGET_X_OFFSET = 10

WORKFLOW_EDIT_CANVAS_X = 1000
WORKFLOW_EDIT_CANVAS_Y = 600

PARAM_INPUT_WIDGET_HEIGHT = 22
PARAM_INPUT_WIDGET_WIDTH = 410
PARAM_INPUT_EDIT_WIDTH = 255
PARAM_INPUT_TEXT_WIDTH = 120
PARAM_INPUT_UNIT_WIDTH = 25

# The width of config widgets for the App Parameters
CONFIG_WIDGET_WIDTH = 300
