QSETTINGS_GLOBAL_KEYS = ['mp_n_workers',
                         'shared_buffer_size',
                         'shared_buffer_max_n',
                         'det_mask',
                         'det_mask_val',
                         'mosaic_border_width',
                         'mosaic_border_value',
                         'mosaic_max_size',
                         'plugin_path',
                         'plot_update_time']
