GENERIC_PLUGIN_WIDGET_WIDTH = 165
GENERIC_PLUGIN_WIDGET_HEIGHT = 35
GENERIC_PLUGIN_WIDGET_Y_OFFSET = 30
GENERIC_PLUGIN_WIDGET_X_OFFSET = 10

WORKFLOW_EDIT_CANVAS_X = 1000
WORKFLOW_EDIT_CANVAS_Y = 600

PARAM_INPUT_WIDGET_HEIGHT = 22